name: Run Postman Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman and HTML reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Set Base URL in Environment
        run: |
          # Zamijeni baseUrl sa tvojim API-jem, npr. JSONPlaceholder
          jq '.values += [{"key":"baseUrl","value":"https://jsonplaceholder.typicode.com","type":"text"}]' \
          postman/environment/Blog\ API\ Testing.postman_environment.json > temp.json
          mv temp.json postman/environment/Blog\ API\ Testing.postman_environment.json

      - name: Run Postman Collection
        run: |
          newman run "postman/collections/Blog API Testing.postman_collections.json" \
          -e "postman/environment/Blog API Testing.postman_environment.json" \
          -r cli,html --reporter-html-export "reports/Blog-API-Test-Report.html"
